#version: '3.8'
services:
  app:
    container_name: oasd_app
    build:
      dockerfile: ./php/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
#      - ./public:/var/www/html/public
    depends_on:
      - db
#      - redis

  db:
    image: mysql:8.0
    #    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oasd
      MYSQL_USER: user
      MYSQL_PASSWORD: qwer4321
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

volumes:
  mysql_data:
#  redis_data: